//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by Fernflower decompiler)
//

package dk.mrspring.wasteland.ruin;

import cpw.mods.fml.common.IWorldGenerator;
import dk.mrspring.wasteland.config.ModConfig;
import dk.mrspring.wasteland.items.LootStack;
import dk.mrspring.wasteland.utils.CustomItemStack;
import dk.mrspring.wasteland.utils.Rectangle;
import dk.mrspring.wasteland.utils.Vector;
import net.minecraft.block.Block;
import net.minecraft.init.Blocks;
import net.minecraft.tileentity.TileEntityChest;
import net.minecraft.world.World;

import java.util.Random;

public class RuinSurvivorTent extends Ruin implements IWorldGenerator
{
    private RuinGenHelper genHelper = new RuinGenHelper();

    public RuinSurvivorTent(String par1Name)
    {
        super(par1Name);
    }

    public boolean generate(World world, Random random, int x, int y, int z)
    {
        RuinGenHelper var10000 = this.genHelper;
        RuinGenHelper.setWorld(world);
        Rectangle pos = new Rectangle(new Vector(x - 2, y, z - 3), 5, 6);
        Block biomeBlock = ModConfig.getSurfaceBlock();
        int biomeBlockMeta = ModConfig.getSurfaceBlockMeta();
        int[] levels = Layout.getLevels(world, pos);
        if (Layout.checkLevel(levels, 0))
        {
            int yCoord = Layout.getAverageLevel(levels) - 1;
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z - 3, biomeBlock, biomeBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z - 2, biomeBlock, biomeBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z - 1, biomeBlock, biomeBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z + 0, biomeBlock, biomeBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z + 1, biomeBlock, biomeBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z + 2, biomeBlock, biomeBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z - 3, biomeBlock, biomeBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z - 2, biomeBlock, biomeBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z - 1, biomeBlock, biomeBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z + 0, Blocks.chest);
            TileEntityChest chest = (TileEntityChest) world.getTileEntity(x - 1, yCoord, z);
            LootStack loot = this.setItems(random);
            CustomItemStack.placeLoot(random, chest, CustomItemStack.getLootItems(random, loot.items, loot.minNum, loot.maxNum, loot.repeat));
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z + 1, biomeBlock, biomeBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z + 2, biomeBlock, biomeBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x, yCoord, z - 3, biomeBlock, biomeBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x, yCoord, z - 2, biomeBlock, biomeBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x, yCoord, z - 1, Blocks.planks);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x, yCoord, z + 0, Blocks.planks);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x, yCoord - 1, z + 0, Blocks.tnt);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x, yCoord, z + 1, Blocks.planks);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x, yCoord, z + 2, biomeBlock);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 1, yCoord, z - 3, biomeBlock, biomeBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 1, yCoord, z - 2, biomeBlock, biomeBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 1, yCoord, z - 1, biomeBlock, biomeBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 1, yCoord, z + 0, biomeBlock, biomeBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 1, yCoord, z + 1, biomeBlock, biomeBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 1, yCoord, z + 2, biomeBlock, biomeBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 2, yCoord, z - 3, biomeBlock, biomeBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 2, yCoord, z - 2, biomeBlock, biomeBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 2, yCoord, z - 1, biomeBlock, biomeBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 2, yCoord, z + 0, biomeBlock, biomeBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 2, yCoord, z + 1, biomeBlock, biomeBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 2, yCoord, z + 2, biomeBlock, biomeBlockMeta);
            ++yCoord;
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z - 3, Blocks.wool);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z - 2, Blocks.wool);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z - 1, Blocks.wool);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z + 0, Blocks.wool);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z + 1, Blocks.wool);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z + 2, Blocks.wool);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z - 3, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z - 2, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z - 1, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z + 0, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z + 1, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z + 2, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x, yCoord, z - 3, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x, yCoord, z - 2, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x, yCoord, z - 1, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x, yCoord, z + 0, Blocks.wooden_pressure_plate);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x, yCoord, z + 1, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x, yCoord, z + 2, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 1, yCoord, z - 3, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 1, yCoord, z - 2, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 1, yCoord, z - 1, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 1, yCoord, z + 0, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 1, yCoord, z + 1, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 1, yCoord, z + 2, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 2, yCoord, z - 3, Blocks.wool);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 2, yCoord, z - 2, Blocks.wool);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 2, yCoord, z - 1, Blocks.wool);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 2, yCoord, z + 0, Blocks.wool);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 2, yCoord, z + 1, Blocks.wool);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 2, yCoord, z + 2, Blocks.wool);
            ++yCoord;
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z - 3, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z - 2, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z - 1, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z + 0, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z + 1, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z + 2, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z - 3, Blocks.wool);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z - 2, Blocks.wool);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z - 1, Blocks.wool);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z + 0, Blocks.wool);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z + 1, Blocks.wool);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z + 2, Blocks.wool);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x, yCoord, z - 3, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x, yCoord, z - 2, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x, yCoord, z - 1, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x, yCoord, z + 0, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x, yCoord, z + 1, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x, yCoord, z + 2, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 1, yCoord, z - 3, Blocks.wool);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 1, yCoord, z - 2, Blocks.wool);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 1, yCoord, z - 1, Blocks.wool);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 1, yCoord, z + 0, Blocks.wool);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 1, yCoord, z + 1, Blocks.wool);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 1, yCoord, z + 2, Blocks.wool);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 2, yCoord, z - 3, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 2, yCoord, z - 2, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 2, yCoord, z - 1, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 2, yCoord, z + 0, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 2, yCoord, z + 1, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 2, yCoord, z + 2, Blocks.air);
            ++yCoord;
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z - 3, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z - 2, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z - 1, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z + 0, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z + 1, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z + 2, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x, yCoord, z - 3, Blocks.wool);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x, yCoord, z - 2, Blocks.wool);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x, yCoord, z - 1, Blocks.wool);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x, yCoord, z + 0, Blocks.wool);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x, yCoord, z + 1, Blocks.wool);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x, yCoord, z + 2, Blocks.wool);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 1, yCoord, z - 3, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 1, yCoord, z - 2, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 1, yCoord, z - 1, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 1, yCoord, z + 0, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 1, yCoord, z + 1, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 1, yCoord, z + 2, Blocks.air);
            return true;
        } else
        {
            return false;
        }
    }
}
