//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by Fernflower decompiler)
//

package dk.mrspring.wasteland.ruin;

import cpw.mods.fml.common.IWorldGenerator;
import dk.mrspring.wasteland.ModHelper;
import dk.mrspring.wasteland.items.LootStack;
import dk.mrspring.wasteland.utils.CustomItemStack;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraft.tileentity.TileEntityChest;
import net.minecraft.world.World;

import java.util.Random;

public class RuinSpawner extends Ruin implements IWorldGenerator
{
    private RuinGenHelper genHelper = new RuinGenHelper();

    public RuinSpawner(String name)
    {
        super(name);
    }

    protected boolean generate(World world, Random random, int xCoord, int yCoord, int zCoord)
    {
        if (world.getHeightValue(xCoord + 4, zCoord - 2) == yCoord && world.getHeightValue(xCoord + 4, zCoord - 1) == yCoord && world.getHeightValue(xCoord + 4, zCoord + 0) == yCoord && world.getHeightValue(xCoord + 4, zCoord + 1) == yCoord && world.getHeightValue(xCoord + 4, zCoord + 2) == yCoord && world.getHeightValue(xCoord + 4, zCoord + 3) == yCoord && world.getHeightValue(xCoord + 4, zCoord + 4) == yCoord && world.getHeightValue(xCoord + 3, zCoord - 2) == yCoord && world.getHeightValue(xCoord + 3, zCoord + 5) == yCoord && world.getHeightValue(xCoord + 2, zCoord - 2) == yCoord && world.getHeightValue(xCoord + 2, zCoord + 5) == yCoord && world.getHeightValue(xCoord + 1, zCoord - 2) == yCoord && world.getHeightValue(xCoord + 1, zCoord + 5) == yCoord && world.getHeightValue(xCoord + 0, zCoord - 2) == yCoord && world.getHeightValue(xCoord + 0, zCoord + 5) == yCoord && world.getHeightValue(xCoord - 1, zCoord - 2) == yCoord && world.getHeightValue(xCoord - 1, zCoord + 5) == yCoord && world.getHeightValue(xCoord - 2, zCoord - 2) == yCoord && world.getHeightValue(xCoord - 2, zCoord + 5) == yCoord && world.getHeightValue(xCoord - 3, zCoord - 2) == yCoord && world.getHeightValue(xCoord - 3, zCoord + 5) == yCoord && world.getHeightValue(xCoord - 4, zCoord - 2) == yCoord && world.getHeightValue(xCoord - 4, zCoord + 5) == yCoord)
        {
            System.out.println("Generating Succesfully at: " + ModHelper.getCoordAsString(xCoord, yCoord, zCoord));
            RuinGenHelper var10000 = this.genHelper;
            RuinGenHelper.setWorld(world);
            --yCoord;
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 0, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 4, Blocks.chest);
            TileEntityChest chest = (TileEntityChest) world.getTileEntity(xCoord + 4, yCoord, zCoord + 4);
            LootStack loot = this.setItems(random);
            CustomItemStack.placeLoot(random, chest, CustomItemStack.getLootItems(random, loot.items, loot.minNum, loot.maxNum, loot.repeat));
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 0, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 1, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 2, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 3, Blocks.planks);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord - 1, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 0, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 1, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 2, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord - 1, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 0, Blocks.planks);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 1, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 2, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 3, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord - 2, Blocks.stone_stairs);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord - 1, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 0, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 1, Blocks.planks);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 2, Blocks.planks);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 3, Blocks.air);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 4, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 0, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 1, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 0, Blocks.cobblestone);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 1, Blocks.planks);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 2, Blocks.cobblestone);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 3, Blocks.cobblestone);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 4, Blocks.netherrack);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 2, yCoord + 1, zCoord + 4, Blocks.fire);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord - 1, Blocks.planks);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord + 0, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord + 1, Blocks.cobblestone);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord + 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord + 4, Blocks.cobblestone);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord + 5, Blocks.cobblestone);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 4, yCoord, zCoord + 2, Blocks.planks);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 4, yCoord, zCoord + 1, Blocks.cobblestone);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 4, yCoord, zCoord + 0, Blocks.planks);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 4, yCoord, zCoord + 1, Blocks.cobblestone);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 4, yCoord, zCoord + 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 4, yCoord, zCoord + 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord - 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord + 0, Blocks.cobblestone);
            ++yCoord;
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 2, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 1, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 0, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 1, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 2, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 4, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 5, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord - 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 5, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 3, world.getHeightValue(xCoord + 3, zCoord - 4), zCoord - 4, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord - 2, Blocks.cobblestone);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 5, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 5, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord - 2, Blocks.cobblestone);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 5, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord - 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 5, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord - 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord - 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord - 1, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 0, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 1, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 4, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 5, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 2, world.getHeightValue(xCoord - 2, zCoord - 4), zCoord - 4, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord - 2, Blocks.cobblestone);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord - 1, Blocks.cobblestone);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 1, Blocks.cobblestone);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 5, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord - 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 4, yCoord, zCoord - 4, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 4, yCoord, zCoord + 5, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 5, world.getHeightValue(xCoord - 5, zCoord - 5), zCoord - 5, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord - 2, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord - 1, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord + 1, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord + 2, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord + 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord + 4, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord + 5, Blocks.stonebrick, 2);
            ++yCoord;
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 1, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 0, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 1, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 2, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 4, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 5, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord - 2, Blocks.cobblestone);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 5, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 5, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 5, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord - 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 5, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 5, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord - 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord - 1, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 0, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 1, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 2, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 4, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 5, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord - 2, Blocks.cobblestone);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord - 2, Blocks.stone_stairs);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 5, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord - 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord + 5, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 4, yCoord, zCoord + 5, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord - 5, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord - 2, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord - 1, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord + 1, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord + 2, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord + 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord + 4, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord + 5, Blocks.stonebrick, 2);
            ++yCoord;
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 1, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 0, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 1, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 2, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 4, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 5, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord - 1, Blocks.cobblestone);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 5, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 5, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord - 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 5, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 5, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord - 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 5, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord - 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord - 1, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 0, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 1, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 4, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 5, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 5, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord + 5, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord - 1, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord + 0, Blocks.stonebrick, 2);
            ++yCoord;
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 2, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 1, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 0, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 1, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 4, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 5, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 0, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 1, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 5, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord - 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord - 1, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 0, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 1, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 4, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 5, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord - 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord - 1, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 0, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 1, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 2, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 4, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 5, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord - 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord - 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord - 1, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 0, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 1, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 4, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 5, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord - 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord - 1, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 0, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 1, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 4, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 5, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord - 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 0, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 1, Blocks.torch);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 4, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 4, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 5, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord + 4, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord + 5, Blocks.stonebrick);
            ++yCoord;
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 2, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 1, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 0, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 1, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 4, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 5, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 5, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord - 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 5, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord - 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 5, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 5, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 5, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord - 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 5, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord - 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 5, Blocks.stonebrick);
            ++yCoord;
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 2, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 1, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 0, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 1, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 4, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 5, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord - 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 5, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord - 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 5, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 5, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 5, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 5, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 5, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord - 3, Blocks.stonebrick, 2);
            ++yCoord;
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 2, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 1, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 0, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 1, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 2, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 4, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 5, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 5, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 5, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 5, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 5, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 5, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord - 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord - 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord - 3, Blocks.stonebrick, 2);
            ++yCoord;
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 1, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 1, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord - 2, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord - 1, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 0, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 1, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 2, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 4, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 5, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord - 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord - 2, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord - 1, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 0, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 1, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 2, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 4, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 5, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord - 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord - 2, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord - 1, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 0, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 1, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 2, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 4, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 5, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord - 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord - 1, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 0, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 1, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 2, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 4, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 5, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord - 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord - 1, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 0, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 1, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 4, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 5, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord - 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord - 1, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 0, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 1, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 4, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord - 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord - 1, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 0, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 1, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord - 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord + 0, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord + 1, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord + 2, Blocks.stonebrick, 2);
            return true;
        } else
        {
            return false;
        }
    }

    private static ItemStack getLootItem(Random rand, ItemStack[] items)
    {
        int i = rand.nextInt(items.length);
        ItemStack itemStack = new ItemStack(items[i].getItem(), 1);
        return itemStack.getItem() == Items.rotten_flesh ? new ItemStack(itemStack.getItem(), rand.nextInt(4) + 2) : (itemStack.getItem() == Items.bucket ? new ItemStack(itemStack.getItem(), rand.nextInt(3) + 1) : (itemStack.getItem() == Items.spider_eye ? new ItemStack(itemStack.getItem(), rand.nextInt(5) + 1) : (itemStack.getItem() == Items.record_chirp ? new ItemStack(itemStack.getItem(), 1) : (itemStack.getItem() == Items.name_tag ? new ItemStack(itemStack.getItem(), rand.nextInt(1) + 1) : (itemStack.getItem() == Items.potato ? new ItemStack(itemStack.getItem(), rand.nextInt(2) + 1) : (itemStack.getItem() == Items.carrot ? new ItemStack(itemStack.getItem(), rand.nextInt(2) + 1) : (itemStack.getItem() == Items.feather ? new ItemStack(itemStack.getItem(), rand.nextInt(9) + 4) : (itemStack.getItem() == Items.leather_chestplate ? new ItemStack(itemStack.getItem(), 1, itemStack.getMaxDamage() - rand.nextInt(itemStack.getMaxDamage() / 2)) : itemStack))))))));
    }
}
