//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by Fernflower decompiler)
//

package dk.mrspring.wasteland.ruin;

import cpw.mods.fml.common.IWorldGenerator;
import dk.mrspring.wasteland.config.ModConfig;
import dk.mrspring.wasteland.items.LootStack;
import dk.mrspring.wasteland.utils.CustomItemStack;
import dk.mrspring.wasteland.utils.Rectangle;
import dk.mrspring.wasteland.utils.Vector;
import net.minecraft.block.Block;
import net.minecraft.init.Blocks;
import net.minecraft.tileentity.TileEntityChest;
import net.minecraft.world.World;

import java.util.Random;

public class RuinRuined extends Ruin implements IWorldGenerator
{
    private RuinGenHelper genHelper = new RuinGenHelper();

    public RuinRuined(String par1Name)
    {
        super(par1Name);
    }

    public boolean generate(World world, Random rand, int x, int y, int z)
    {
        RuinGenHelper var10000 = this.genHelper;
        RuinGenHelper.setWorld(world);
        Rectangle pos = new Rectangle(new Vector(x - 5, y, z - 6), 10, 12);
        int[] lay = Layout.getLevels(world, pos);
        Block surfaceBlock = ModConfig.getSurfaceBlock();
        int surfaceBlockMeta = ModConfig.getSurfaceBlockMeta();
        if (Layout.checkLevel(lay, 3))
        {
            int yCoord = Layout.getMinLevel(lay);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 4, yCoord, z - 2, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 4, yCoord, z - 1, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 4, yCoord, z + 0, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 4, yCoord, z + 1, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 4, yCoord, z + 2, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 4, yCoord, z + 3, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 4, yCoord, z + 6, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 3, yCoord, z - 3, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 3, yCoord, z - 2, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 3, yCoord, z - 1, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 3, yCoord, z + 0, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 3, yCoord, z + 1, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 3, yCoord, z + 2, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 3, yCoord, z + 3, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 3, yCoord, z + 4, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 2, yCoord, z - 4, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 2, yCoord, z - 3, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 2, yCoord, z - 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 2, yCoord, z - 1, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 2, yCoord, z + 0, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 2, yCoord, z + 1, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 2, yCoord, z + 2, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 2, yCoord, z + 3, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 2, yCoord, z + 4, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 2, yCoord, z + 5, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 2, yCoord, z + 7, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 1, yCoord, z - 4, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 1, yCoord, z - 3, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 1, yCoord, z - 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 1, yCoord, z - 1, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 1, yCoord, z + 0, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 1, yCoord, z + 1, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 1, yCoord, z + 2, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 1, yCoord, z + 3, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 1, yCoord, z + 4, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 1, yCoord, z + 5, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 0, yCoord, z - 4, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 0, yCoord, z - 3, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 0, yCoord, z - 2, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 0, yCoord, z - 1, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 0, yCoord, z + 0, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 0, yCoord, z + 1, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 0, yCoord, z + 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 0, yCoord, z + 3, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 0, yCoord, z + 4, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 0, yCoord, z + 5, surfaceBlock);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z - 4, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z - 3, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z - 2, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z - 1, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z + 0, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z + 1, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z + 2, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z + 3, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z + 4, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z + 5, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z - 7, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z - 4, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z - 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z - 2, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z - 1, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z + 0, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z + 1, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z + 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z + 3, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z + 4, Blocks.netherrack);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z + 5, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 3, yCoord, z - 4, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 3, yCoord, z - 3, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 3, yCoord, z - 2, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 3, yCoord, z - 1, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 3, yCoord, z + 0, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 3, yCoord, z + 1, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 3, yCoord, z + 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 3, yCoord, z + 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 3, yCoord, z + 4, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 3, yCoord, z + 5, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 4, yCoord, z - 4, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 4, yCoord, z - 3, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 4, yCoord, z - 2, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 4, yCoord, z - 1, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 4, yCoord, z + 0, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 4, yCoord, z + 1, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 4, yCoord, z + 2, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 4, yCoord, z + 3, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 4, yCoord, z + 4, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 5, yCoord, z - 6, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 5, yCoord, z - 2, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 5, yCoord, z - 1, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 5, yCoord, z + 0, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 5, yCoord, z + 1, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 5, yCoord, z + 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 5, yCoord, z + 3, surfaceBlock, surfaceBlockMeta);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 6, yCoord, z - 6, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 7, yCoord, z - 4, Blocks.stonebrick, 2);
            ++yCoord;
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 7, yCoord, z + 4, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 5, yCoord, z + 5, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 5, yCoord, z + 7, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 4, yCoord, z - 2, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 4, yCoord, z - 1, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 4, yCoord, z + 0, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 4, yCoord, z + 1, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 4, yCoord, z + 2, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 4, yCoord, z + 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 3, yCoord, z - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 3, yCoord, z - 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 2, yCoord, z - 4, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 2, yCoord, z - 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 2, yCoord, z - 1, Blocks.stone_stairs);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 2, yCoord, z + 1, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 2, yCoord, z + 5, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 1, yCoord, z - 4, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 1, yCoord, z + 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 1, yCoord, z + 5, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 0, yCoord, z - 6, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 0, yCoord, z - 4, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 0, yCoord, z - 1, Blocks.cobblestone);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 0, yCoord, z + 1, Blocks.log);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 0, yCoord, z + 5, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z - 4, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z - 3, Blocks.cobblestone);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z - 2, Blocks.cobblestone);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z + 5, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z - 4, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z + 4, Blocks.fire);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z + 5, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 3, yCoord, z - 4, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 3, yCoord, z - 2, Blocks.stone_stairs);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 3, yCoord, z + 4, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 3, yCoord, z + 5, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 4, yCoord, z - 4, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 4, yCoord, z - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 4, yCoord, z - 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 4, yCoord, z + 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 4, yCoord, z + 4, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 5, yCoord, z - 2, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 5, yCoord, z + 3, Blocks.stonebrick, 2);
            ++yCoord;
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 4, yCoord, z - 2, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 4, yCoord, z - 1, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 4, yCoord, z + 0, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 4, yCoord, z + 1, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 4, yCoord, z + 2, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 3, yCoord, z - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 2, yCoord, z - 4, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 1, yCoord, z - 4, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 1, yCoord, z + 5, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 0, yCoord, z - 4, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 0, yCoord, z + 1, Blocks.log);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 0, yCoord, z + 5, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z - 4, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z - 3, Blocks.cobblestone);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z + 5, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z - 4, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z - 3, Blocks.cobblestone);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z + 5, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 3, yCoord, z - 4, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 3, yCoord, z + 5, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 4, yCoord, z - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 4, yCoord, z + 4, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 5, yCoord, z - 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 5, yCoord, z + 3, Blocks.stonebrick, 2);
            ++yCoord;
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 4, yCoord, z - 2, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 4, yCoord, z - 1, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 4, yCoord, z + 0, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 4, yCoord, z + 1, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 4, yCoord, z + 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 3, yCoord, z - 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 2, yCoord, z - 4, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 1, yCoord, z - 4, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 1, yCoord, z - 3, Blocks.cobblestone);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 0, yCoord, z - 4, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 0, yCoord, z + 1, Blocks.log);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 0, yCoord, z + 5, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z - 4, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z - 3, Blocks.stone_stairs);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z + 5, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z - 4, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 3, yCoord, z - 4, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 4, yCoord, z - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 4, yCoord, z + 4, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 5, yCoord, z - 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 5, yCoord, z + 3, Blocks.stonebrick, 2);
            ++yCoord;
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 4, yCoord, z - 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 4, yCoord, z - 1, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 4, yCoord, z + 0, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 4, yCoord, z + 1, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 3, yCoord, z - 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 3, yCoord, z - 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 2, yCoord, z - 4, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 2, yCoord, z - 3, Blocks.cobblestone);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 1, yCoord, z - 4, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 0, yCoord, z - 4, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 0, yCoord, z + 1, Blocks.log);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 0, yCoord, z + 2, Blocks.log);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 0, yCoord, z + 5, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z - 4, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z - 4, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 3, yCoord, z + 5, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 4, yCoord, z - 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 4, yCoord, z + 4, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 5, yCoord, z - 2, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 5, yCoord, z + 3, Blocks.stonebrick);
            ++yCoord;
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 4, yCoord, z - 2, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 4, yCoord, x - 1, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 4, yCoord, z + 0, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 4, yCoord, z + 1, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 3, yCoord, z - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 3, yCoord, z + 0, Blocks.cobblestone);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 2, yCoord, z - 4, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 2, yCoord, z + 1, Blocks.log);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 1, yCoord, z - 4, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 1, yCoord, z + 1, Blocks.log);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 0, yCoord, z - 4, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 0, yCoord, z - 1, Blocks.log);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 0, yCoord, z + 0, Blocks.log);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 0, yCoord, z + 1, Blocks.log);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 0, yCoord, z + 3, Blocks.log);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z - 4, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z + 1, Blocks.log);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z + 5, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z - 4, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z + 5, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 3, yCoord, z + 5, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 4, yCoord, z + 4, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 5, yCoord, z - 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 5, yCoord, z - 1, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 5, yCoord, z + 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 5, yCoord, z + 3, Blocks.stonebrick);
            ++yCoord;
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 4, yCoord, z - 2, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 4, yCoord, z - 1, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 4, yCoord, z + 0, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 3, yCoord, z - 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 2, yCoord, z - 4, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 1, yCoord, z - 4, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 0, yCoord, z - 4, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 0, yCoord, z + 1, Blocks.log);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z - 4, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, x + 5, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z - 4, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z + 5, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 3, yCoord, z - 4, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 3, yCoord, z + 5, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 4, yCoord, z - 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 4, yCoord, z + 4, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 5, yCoord, z - 2, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 5, yCoord, z - 1, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 5, yCoord, z + 1, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 5, yCoord, z + 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 5, yCoord, z + 3, Blocks.stonebrick, 2);
            ++yCoord;
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 4, yCoord, z - 2, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 4, yCoord, z - 1, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 4, yCoord, z + 0, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 2, yCoord, z - 4, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 1, yCoord, z - 4, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 0, yCoord, z - 4, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 0, yCoord, z - 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 0, yCoord, z + 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 0, yCoord, z + 4, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z - 4, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z - 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z - 2, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z + 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z + 4, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 1, yCoord, z + 5, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z - 4, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z - 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z - 1, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z + 0, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z + 4, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z + 5, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 3, yCoord, z - 4, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 3, yCoord, z - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 3, yCoord, z - 2, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 3, yCoord, z - 1, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 3, yCoord, z + 0, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 3, yCoord, z + 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 3, yCoord, z + 4, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 3, yCoord, z + 5, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 4, yCoord, z - 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 4, yCoord, z - 2, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 4, yCoord, z - 1, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 4, yCoord, z + 0, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 4, yCoord, z + 1, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 4, yCoord, z + 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 4, yCoord, z + 4, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 5, yCoord, z - 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 5, yCoord, z - 1, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 5, yCoord, z + 0, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 5, yCoord, z + 1, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 5, yCoord, z + 3, Blocks.stonebrick, 2);
            ++yCoord;
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x + 4, yCoord, z - 1, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 2, yCoord, z + 5, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 3, yCoord, z - 4, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 4, yCoord, z - 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 4, yCoord, z - 2, Blocks.chest);
            TileEntityChest chest = (TileEntityChest) world.getTileEntity(x - 4, yCoord, z - 2);
            LootStack loot = this.setItems(rand);
            CustomItemStack.placeLoot(rand, chest, CustomItemStack.getLootItems(rand, loot.items, loot.minNum, loot.maxNum, loot.repeat));
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 4, yCoord, z + 4, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 5, yCoord, z - 2, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 5, yCoord, z - 1, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 5, yCoord, z + 0, Blocks.stonebrick);
            ++yCoord;
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 3, yCoord, z - 4, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 4, yCoord, z - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 5, yCoord, z - 2, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 5, yCoord, z - 1, Blocks.stonebrick);
            ++yCoord;
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 4, yCoord, z - 3, Blocks.stonebrick, 2);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 5, yCoord, z - 2, Blocks.stonebrick, 2);
            ++yCoord;
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 4, yCoord, z - 3, Blocks.stonebrick);
            var10000 = this.genHelper;
            RuinGenHelper.setBlock(x - 5, yCoord, z - 2, Blocks.stonebrick);
            return true;
        } else
        {
            return false;
        }
    }
}
