package dk.mrspring.wasteland.ruin;

import dk.mrspring.wasteland.ModHelper;
import dk.mrspring.wasteland.items.LootStack;
import dk.mrspring.wasteland.ruin.Ruin;
import dk.mrspring.wasteland.ruin.RuinGenHelper;
import dk.mrspring.wasteland.utils.CustomItemStack;
import java.util.Random;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraft.tileentity.TileEntityChest;
import net.minecraft.util.BlockPos;
import net.minecraft.world.World;
import net.minecraftforge.fml.common.IWorldGenerator;

public class RuinSpawner extends Ruin implements IWorldGenerator
{

   private RuinGenHelper genHelper = new RuinGenHelper();


   public RuinSpawner(String name) {
      super(name);
   }

   protected boolean generate(World world, Random random, int xCoord, int yCoord, int zCoord) {
      BlockPos pos = new BlockPos(xCoord, yCoord, zCoord);
      if(world.getHeight(pos.add(4, 0, -2)).getY() == yCoord &&
              world.getHeight(pos.add(4, 0, -1)).getY() == yCoord &&
              world.getHeight(pos.add(4, 0, 0)).getY() == yCoord &&
              world.getHeight(pos.add(4, 0, 1)).getY() == yCoord &&
              world.getHeight(pos.add(4, 0, 2)).getY() == yCoord &&
              world.getHeight(pos.add(4, 0, 3)).getY() == yCoord &&
              world.getHeight(pos.add(4, 0, 4)).getY() == yCoord &&
              world.getHeight(pos.add(3, 0, -2)).getY() == yCoord &&
              world.getHeight(pos.add(3, 0, 5)).getY() == yCoord &&
              world.getHeight(pos.add(2, 0, -2)).getY() == yCoord &&
              world.getHeight(pos.add(2, 0, 5)).getY() == yCoord &&
              world.getHeight(pos.add(1, 0, -2)).getY() == yCoord &&
              world.getHeight(pos.add(1, 0, 5)).getY() == yCoord &&
              world.getHeight(pos.add(0, 0, -2)).getY() == yCoord &&
              world.getHeight(pos.add(0, 0, 5)).getY() == yCoord &&
              world.getHeight(pos.add(-1, 0, -2)).getY() == yCoord &&
              world.getHeight(pos.add(-1, 0, 5)).getY() == yCoord &&
              world.getHeight(pos.add(-2, 0, -2)).getY() == yCoord &&
              world.getHeight(pos.add(-2, 0, 5)).getY() == yCoord &&
              world.getHeight(pos.add(-3, 0, -2)).getY() == yCoord &&
              world.getHeight(pos.add(-3, 0, 5)).getY() == yCoord &&
              world.getHeight(pos.add(-4, 0, -2)).getY() == yCoord &&
              world.getHeight(pos.add(-4, 0, 5)).getY() == yCoord) {
         System.out.println("Generating Succesfully at: " + ModHelper.getCoordAsString(xCoord, yCoord, zCoord));
         RuinGenHelper.setWorld(world);
         --yCoord;
         RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 0, Blocks.air);
         RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 3, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 4, Blocks.chest);
         TileEntityChest chest = (TileEntityChest)world.getTileEntity(pos.add(4, 0, 4)/*xCoord + 4, yCoord, zCoord + 4*/);
         LootStack loot = this.setItems(random);
         CustomItemStack.placeLoot(random, chest, CustomItemStack.getLootItems(random, loot.items, loot.minNum, loot.maxNum, loot.repeat));
         RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 0, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 1, Blocks.air);
         RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 2, Blocks.air);
         RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 3, Blocks.planks);
         RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord - 1, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 0, Blocks.air);
         RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 1, Blocks.air);
         RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 2, Blocks.air);
         RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 3, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord - 1, Blocks.air);
         RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 0, Blocks.planks);
         RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 1, Blocks.air);
         RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 2, Blocks.air);
         RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 3, Blocks.air);
         RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord - 2, Blocks.stone_stairs);
         RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord - 1, Blocks.air);
         RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 0, Blocks.air);
         RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 1, Blocks.planks);
         RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 2, Blocks.planks);
         RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 3, Blocks.air);
         RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 4, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 0, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 1, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 2, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 0, Blocks.cobblestone);
         RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 1, Blocks.planks);
         RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 2, Blocks.cobblestone);
         RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 3, Blocks.cobblestone);
         RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 4, Blocks.netherrack);
         RuinGenHelper.setBlock(xCoord - 2, yCoord + 1, zCoord + 4, Blocks.fire);
         RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord - 1, Blocks.planks);
         RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord + 0, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord + 1, Blocks.cobblestone);
         RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord + 3, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord + 4, Blocks.cobblestone);
         RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord + 5, Blocks.cobblestone);
         RuinGenHelper.setBlock(xCoord - 4, yCoord, zCoord + 2, Blocks.planks);
         RuinGenHelper.setBlock(xCoord - 4, yCoord, zCoord + 1, Blocks.cobblestone);
         RuinGenHelper.setBlock(xCoord - 4, yCoord, zCoord + 0, Blocks.planks);
         RuinGenHelper.setBlock(xCoord - 4, yCoord, zCoord + 1, Blocks.cobblestone);
         RuinGenHelper.setBlock(xCoord - 4, yCoord, zCoord + 2, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 4, yCoord, zCoord + 3, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord - 3, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord + 0, Blocks.cobblestone);
         ++yCoord;
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 2, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 1, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 0, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 1, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 2, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 4, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 5, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord - 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord - 2, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 2, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 5, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 3, zCoord - 4, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord - 2, Blocks.cobblestone);
         RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 5, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord - 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 5, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord - 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord - 2, Blocks.cobblestone);
         RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 5, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord - 3, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 5, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord - 3, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord - 2, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord - 1, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 0, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 1, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 2, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 3, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 4, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 5, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord - 2, zCoord - 4, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord - 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord - 2, Blocks.cobblestone);
         RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord - 1, Blocks.cobblestone);
         RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 1, Blocks.cobblestone);
         RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 5, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord - 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord - 2, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 4, yCoord, zCoord - 4, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord - 4, yCoord, zCoord + 5, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord - 5, zCoord - 5, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord - 2, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord - 1, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord + 1, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord + 2, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord + 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord + 4, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord + 5, Blocks.stonebrick, 2);
         ++yCoord;
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 2, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 1, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 0, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 1, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 2, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 4, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 5, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord - 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord - 2, Blocks.cobblestone);
         RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 5, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord - 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 5, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord - 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 5, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord - 3, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 5, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord - 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 5, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord - 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord - 2, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord - 1, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 0, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 1, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 2, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 3, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 4, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 5, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord - 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord - 2, Blocks.cobblestone);
         RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord - 2, Blocks.stone_stairs);
         RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 5, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord - 3, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord + 5, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 4, yCoord, zCoord + 5, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord - 5, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord - 2, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord - 1, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord + 1, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord + 2, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord + 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord + 4, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord + 5, Blocks.stonebrick, 2);
         ++yCoord;
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 2, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 1, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 0, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 1, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 2, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 3, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 4, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 5, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord - 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord - 1, Blocks.cobblestone);
         RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 5, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord - 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 5, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord - 3, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 5, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord - 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 5, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord - 2, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 5, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord - 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord - 2, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord - 1, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 0, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 1, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 2, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 4, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 5, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord - 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 5, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord + 5, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord - 1, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord + 0, Blocks.stonebrick, 2);
         ++yCoord;
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 2, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 1, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 0, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 1, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 2, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 4, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 5, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord - 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 0, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 1, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 3, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 5, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord - 3, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord - 1, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 0, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 1, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 2, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 4, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 5, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord - 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord - 2, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord - 1, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 0, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 1, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 2, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 4, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 5, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord - 3, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord - 2, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord - 1, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 0, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 1, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 2, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 4, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 5, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord - 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord - 2, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord - 1, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 0, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 1, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 2, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 3, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 4, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 5, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord - 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord - 2, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 0, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 1, Blocks.torch);
         RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 3, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 4, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 3, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 4, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 5, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord + 4, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord + 5, Blocks.stonebrick);
         ++yCoord;
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 2, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 1, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 0, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 1, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 2, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 4, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 5, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord - 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 5, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord - 3, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 5, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord - 3, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 5, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord - 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 5, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord - 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 5, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord - 3, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 5, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord - 3, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 5, Blocks.stonebrick);
         ++yCoord;
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 2, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 1, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 0, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 1, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 2, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 3, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 4, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 5, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord - 3, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 5, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord - 3, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 5, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord - 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 5, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord - 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 5, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord - 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 5, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord - 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 5, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord - 3, Blocks.stonebrick, 2);
         ++yCoord;
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 2, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 1, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 0, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 1, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 2, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 4, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 5, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord - 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 5, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord - 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 5, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord - 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 5, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord - 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 5, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord - 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 5, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord - 3, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord - 3, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord - 3, Blocks.stonebrick, 2);
         ++yCoord;
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 1, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 1, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 2, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 3, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord - 2, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord - 1, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 0, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 1, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 2, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 4, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 5, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord - 3, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord - 2, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord - 1, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 0, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 1, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 2, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 4, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 5, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord - 3, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord - 2, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord - 1, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 0, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 1, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 2, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 4, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 5, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord - 2, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord - 1, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 0, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 1, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 2, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 4, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 5, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord - 2, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord - 1, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 0, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 1, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 2, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 3, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 4, Blocks.stonebrick);
         RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 5, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord - 2, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord - 1, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 0, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 1, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 2, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 3, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 4, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord - 2, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord - 1, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 0, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 1, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 2, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 3, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord - 2, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord + 0, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord + 1, Blocks.stonebrick, 2);
         RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord + 2, Blocks.stonebrick, 2);
         return true;
      } else {
         return false;
      }
   }

   private static ItemStack getLootItem(Random rand, ItemStack[] items) {
      int i = rand.nextInt(items.length);
      ItemStack itemStack = new ItemStack(items[i].getItem(), 1);
      return itemStack.getItem() == Items.rotten_flesh?new ItemStack(itemStack.getItem(), rand.nextInt(4) + 2):(itemStack.getItem() == Items.bucket?new ItemStack(itemStack.getItem(), rand.nextInt(3) + 1):(itemStack.getItem() == Items.spider_eye?new ItemStack(itemStack.getItem(), rand.nextInt(5) + 1):(itemStack.getItem() == Items.record_chirp?new ItemStack(itemStack.getItem(), 1):(itemStack.getItem() == Items.name_tag?new ItemStack(itemStack.getItem(), rand.nextInt(1) + 1):(itemStack.getItem() == Items.potato?new ItemStack(itemStack.getItem(), rand.nextInt(2) + 1):(itemStack.getItem() == Items.carrot?new ItemStack(itemStack.getItem(), rand.nextInt(2) + 1):(itemStack.getItem() == Items.feather?new ItemStack(itemStack.getItem(), rand.nextInt(9) + 4):(itemStack.getItem() == Items.leather_chestplate?new ItemStack(itemStack.getItem(), 1, itemStack.getMaxDamage() - rand.nextInt(itemStack.getMaxDamage() / 2)):itemStack))))))));
   }
}
